<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'An error occurred while installing Rights.' => 'Произошла ошибка при установке Rights',
  'Application authorization manager must extend the RDbAuthManager class.' => 'Менеджер авторизации приложения должен наследовать класс RDbAuthManager',
  'Application web user must extend the RWebUser class.' => 'Пользователь приложения (WebUser) должен наследовать класс RWebUser',
  'Congratulations!' => 'Поздравляем!',
  'Error' => 'Ошибка',
  'Install Rights' => 'Установить Rights',
  'No' => 'Нет',
  'Notice: All your existing data will be lost.' => 'Внимание: все ваши данные будут потеряны.',
  'Please confirm if you wish to reinstall.' => 'Пожалуйста, подтвердите переустановку.',
  'Please try again or consult the documentation.' => 'Пожалуйста, попробуйте еще ​​раз или обратитесь к документации.',
  'Rights has been installed succesfully.' => 'Rights успешно установлен.',
  'Rights is already installed!' => 'Rights уже установлен!',
  'Yes' => 'Да',
  'You can start by generating your authorization items' => 'Вы можете начать с создания элементов авторизации',
  'You must be logged in to install Rights.' => 'Вы должны быть зарегистрированы, чтобы установить Rights',
  'here' => 'здесь',
);